### ISSUE TITLE
Render the obj into complex background images?

### ISSUE THREAD

**Issue by zy20091082** [jackd/shapenet#1]
Thanks for your great tools for shapenet? Can it render the .obj with complex background images?

**Comment by jackd** [comment]
I'd rather keep this repository to mostly simple data loading and format conversions (meshes, renderings, binvox, point clouds etc.). There's nothing to stop you combining the images in your own work though. See example below. Note that while this uses the same background image, you could load a different one each time. It won't make the lighting consistent, but that's a much larger job, beyond the scope of this repo.

```
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from shapenet.core.blender_renderings.config import RenderConfig
from shapenet.core import cat_desc_to_id


def get_image_dataset():
	cat_desc = 'plane'
	cat_id = cat_desc_to_id(cat_desc)
	config = RenderConfig()
	return config.get_dataset(cat_id, view_index=5).map(overlayed)


def get_background_image():
	return Image.open('background.jpg').resize((256, 192))

def overlayed(image):
	background = get_background_image()
	background.paste(image, mask=image)
	return background


with get_image_dataset() as image_dataset:
	for key in image_dataset:
		plt.imshow(image_dataset[key])
		plt.show()
		
```
