### ISSUE TITLE
some examples cannot get rendering images

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/shapenet#4]
Hi @jackd ,
When I run `render_cat.py car`, an example item can't be rendered. I have list it below. 
I got 7496 rendering images of car, but also got 7497 point clouds of car. I am afraid that it will cause corresbonding issues..
Rendering 7497 images for cat 02958343
 |████████████████▋               | 3881/7497
2018-05-18 20:02:47.176640
Rendering f9c1d7748c15499c6f2bd1c4e9adb41

the same issue occurs in category `pot` too.
So how can I render this certain example or how can I delete this certain example in point cloud file?

**Comment by jackd** [comment]
If you want to delete the data from the point cloud dataset, the `SavingDataset` supports the `del` (I've just added the optional mode argument which didn't allow this before).

```
with get_point_cloud_dataset(cat_id, n_samples, mode='a') as ds:
  del ds[bad_id]
```

If you want to get a rendering, follow instructions in the subdirectory's [README.md](https://github.com/jackd/shapenet/blob/master/core/blender_renderings/README.md). Short version: import the obj file into meshlab and re-export. Didn't do pots, but it worked for that one annoying car model...

**Comment by jackd** [comment]
Upon further consideration I added more optional mode flags and made a small change to `dids`, so you may have to re-pull there.

**Comment by xiaomingjie** [comment]
It works by re-exporting the model in meshlab!
Thanks a lot！
