### ISSUE TITLE
why there is no create_point.py?

### ISSUE THREAD

**Issue by AmyWan** [jackd/shapenet#5]

**Comment by jackd** [comment]
... that's a very good question. Just pushed a commit fixing this. Added `core/point_clouds/scripts/generate_point_clouds.py`. Also fixed where meshes were being saved (you may want to move any pre-parsed mesh `.hdf5` files from `shapenet/core/meshes/_meshes` to `shapenet/data/core/meshes/` to prevent re-parsing.

Please let me know if you have issues.
