### ISSUE TITLE
Why there is no get_temp_dir?

### ISSUE THREAD

**Issue by luotuoqingshan** [jackd/shapenet#6]
First thanks a lot for your contribution to writing so useful tools. Here is one question.
In `core/blender_renderings/scripts/render_cat.py` there is a line `from shapenet.path import get_temp_dir`, but there is no get_temp_dir. I think this is a simple typo. Does it refer to get_data_dir?

**Comment by jackd** [comment]
Ah, sorry, I changed implementation to tempfile package a while back but apparently didn't update all references. I'll check it out tomorrow, but you can probably replace it with tempfile.mkdtemp if you need a solution before then.

**Comment by jackd** [comment]
Looks like I'd already replaced the function calls and just hadn't removed the import. Just pushed an update. Thanks for the report :)
