### ISSUE TITLE
Why render and pointcloud, mesh scripts have different implementations regarding example_id?

### ISSUE THREAD

**Issue by luotuoqingshan** [jackd/shapenet#7]
Mesh and  pointcloud generators would generate the mesh and pointcloud data for all objects if example_id are not provided so the id folder could be empty. 
I read `example/core/blender_renderings.py, core/blender_renderings/scripts/render_cat.py`, the render needs to load example_id from id folder. 
I would like to generate multi-view data for all objects.

**Comment by jackd** [comment]
Thanks for highlighting this.

For redistributing the data it's often nice to not have to copy the entire obj zip files just for a list of their contents - e.g. if you want to train point cloud/voxel data - hence I introduced the separate ids.txt (which by default is just a saved version of the obj zip files).

I've just pushed a change which automatically generates the ids txt files if they don't exist already. That should have been there anyway. That will generate images for all CAD models except for one bad one (see `get_example_ids`) which has no vertices (from memory this causes an error in blender).

**Comment by luotuoqingshan** [comment]
Hi @jackd ,

Thank you for the update.

I run `python render_cat.py plane -n 1` but get error.
This is traceback.

```
Rendering 4045 images for cat 02691156
 |                                | 1/4045Traceback (most recent call last):
  File "render_cat.py", line 144, in <module>
    args.verbose)
  File "render_cat.py", line 121, in render_cat
    verbose=verbose, file_index=file_index)
  File "render_cat.py", line 91, in render_example
    config, obj_path, cat_dir, call_kwargs, blender_path=blender_path)
  File "render_cat.py", line 38, in render_obj
    ], **call_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I didn't modify any code and my config.yaml is as below:
```
core_dir:             /srv/home/yufan/code/shapenet/ShapeNetCore.v1                                      # directory containing CAT_ID.zip, CAT_ID.csv, taxonomy.json
iccv17_dir:           /data/shapenet2017                                         # directory containing (train)|(test)|(val)_(imgs)|(voxels).zip
core_annotations_dir: /data/shapenet_annotations                                 # directory containing shapenetcore_partanno_segmentation_benchmark_v0.zip and shapenetcore_partanno_v0.zip
created_data_dir:     /srv/home/yufan/code/shapenet/ShapeNetCore.v1                                                     # directory into data created by this repo saves data
voxel_compression:    lzf
```

**Comment by jackd** [comment]
Is `blender` on your path?

Easy check: what's the output of `which blender` from bash?

**Comment by luotuoqingshan** [comment]
Hi @jackd,

Thank you for your quick reply.

The output of `which blender` is `/home/yufan/blender-2.79b-linux-glibc219-x86_64/blender`.

**Comment by luotuoqingshan** [comment]
Sorry I made a mistake. The code works.
