### ISSUE TITLE
test_train_split of category rifle is wrong

### ISSUE THREAD

**Issue by luotuoqingshan** [jackd/shapenet#9]
When using `generate_point_cloud.py` to generate point cloud data of rifle, there are 2372 records in total.
But in test_train_split, there are 1656 records for training, 475 records for testing, 242 records for validation. It seems one record is redundant.
I get one error.
`KeyError: 'key 4a32519f44dc84aabafe26e2eb69ebf4 not present in base'`

**Comment by jackd** [comment]
If you look at the original obj file, this example has no vertices or faces - just vertex textures. I wasn't sure how to handle this, so I filed it under `_bad_objs` (core/objs.py) so it shouldn't come up in `get_example_ids(rifle_id, include_bad=False)`

**Comment by luotuoqingshan** [comment]
Hi @jackd ,

Thank you for your quick reply.
Yes, I seem this obj in `_bad_objs`, but I see in some other issue that it seems there are some other bad objs? Why does `_bad_objs` only contain this one?

**Comment by jackd** [comment]
There's a car model that just couldn't be rendered by blender without a fix... so I just fixed it. Can't remember any other cases... but it's been a while since I've worked on this.

**Comment by luotuoqingshan** [comment]
Thanks a lot!
